CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER IF NOT EXISTS '${WORDPRESS_DB_USER}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* to '${WORDPRESS_DB_USER}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
UPDATE mysql.user SET authentication_string=PASSWORD('${DB_ROOT_PASSWORD}'), plugin='mysql_native_password' WHERE User='${DB_ROOT_USER}';
FLUSH PRIVILEGES;